### PR TITLE
manually revert ethabi to 1.0.1

### PR DESCRIPTION
**Pull request by rphmeier**
1.0.2 -> 1.0.4 were all published today and are all broken (https://github.com/rust-lang/cargo/issues/3877)

Please revert so we can get builds for https://github.com/paritytech/parity working again.

### CODE REVIEW

**Comment by carols10cents** [comment]
I am working on fixing all affected versions at once. The versions should not be removed from the index; they're already in crates.io's database.

I have rolled back the code on crates.io causing a problem, so if you publish a new version it will not be affected.

**Comment by rphmeier** [comment]
I did publish a new version after the rollback (1.0.4) and the problem still persists despite `cargo clean` and `rm -rf ~/.cargo/registry` numerous times.

**Comment by steveklabnik** [comment]
@rphmeier let's give @carols10cents some time to get through this; having a ton of different stuff pop up at once means this is gonna get fixed slower, rather than faster. Thank you for trying to help!

**Comment by carols10cents** [comment]
Please try again, I have pushed https://github.com/rust-lang/crates.io-index/commit/9917d828acd2e091c9e87bba0e300d9199e3fd13

**Comment by rphmeier** [comment]
Yep, that did the trick.

Thanks for clearing this up!

**Pull request closed without merging**
