### PR TITLE
Remove linux_l6470 0.1.1

### PR DESCRIPTION
**Pull request by tjkirch**
I'm not sure how version 0.1.1 showed up, but it's not on crates.io web (https://crates.io/crates/linux_l6470) and the download URL gives a "Not Found" error: https://crates.io/api/v1/crates/linux_l6470/0.1.1/download

The missing download breaks some mirroring processes, so this change proposes to remove the metadata.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! This repository, however, doesn't take PRs, so closing.

**Comment by alexcrichton** [comment]
Currently it is a policy that crates are not deleted, they can only be yanked

**Comment by tjkirch** [comment]
That's fine - many other crates have been yanked without causing this issue.  This is something different.  The metadata still says there's a valid, unyanked 0.1.1 version, but it doesn't exist.  Should we change the metadata to say it was yanked, rather than deleting the line for that version?

**Comment by alexcrichton** [comment]
Unfortunately bugs like that happen from time to time, the current solution is to publish a new version.

cc @sgrif and @carols10cents though, this is a worrisome bug!

**Comment by carols10cents** [comment]
I'm going to make a bug in the crates.io repo for investigating this...

**Comment by carols10cents** [comment]
Issue created: https://github.com/rust-lang/crates.io/issues/1447

**Comment by est31** [comment]
Just for reference, even though this PR got closed `linux_l6470` was removed in commit dffd660dca6382422fa31b41729d21f030ece187

Wondered why it didn't show up as error for me :)

**Pull request closed without merging**
